# Generated by Django 5.1.7 on 2025-03-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_tag_note_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
    ]
