# Generated by Django 5.1.7 on 2025-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_remove_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="notes.tag"),
        ),
    ]
