# Generated by Django 5.1.7 on 2025-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_commenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
