# Generated by Django 5.1.7 on 2025-04-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_category_note_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
